### ISSUE TITLE
Fix: unable to find version `v1.0`

### ISSUE THREAD

**Issue by manh-t** [nimblehq/publish-github-wiki-action#10]
## Issue

When following the `Usage` section in README and run the workflow with `publish-github-wiki-action` in the steps, I got an error.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/60863885/198530334-a7d593c1-6a3f-4b0a-8ac3-15fc81afb74e.png">

 
## Expected

The user can run the workflow with `publish-github-wiki-action` and the correct version.

**Comment by bterone** [comment]
Hi @manh-t, just [released v1.0](https://github.com/nimblehq/publish-github-wiki-action/releases/tag/v1.0) 🎉 
You should not be having this issue anymore :D

**Comment by manh-t** [comment]
@bterone thank you so much, it's so speed 🤩

**Comment by bterone** [comment]
Closing this as it now works with v1.0 🎉
